repos:
  - repo: local
    hooks:
      - id: spriggit-requiem
        name: 'Spriggit: Requiem'
        entry: components/plugins/spriggit.bat
        language: script
        files: ^Requiem\.esp$
      - id: spriggit-requiem-creation-club
        name: 'Spriggit: Requiem - Creation Club'
        entry: components/plugins/spriggit.bat
        language: script
        files: ^Requiem - Creation Club\.esp$
