repos:
  - repo: local
    hooks:
      - id: spriggit-requiem
        name: "Spriggit: Requiem"
        entry: '"C:\Program Files\Git\bin\bash.exe" components/plugins/spriggit.sh'
        language: system
        files: ^Requiem\.esp$
      - id: spriggit-requiem-creation-club
        name: "Spriggit: Requiem - Creation Club"
        entry: '"C:\Program Files\Git\bin\bash.exe" components/plugins/spriggit.sh'
        language: system
        files: ^Requiem - Creation Club\.esp$
