Scriptname Req_VampireDustScript extends activemagiceffect  

SPELL Property DiseaseSanguinareVampiris  Auto  



Event OnEffectStart(Actor Target, Actor Caster)

	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)
	Target.AddSpell(DiseaseSanguinareVampiris, false)


EndEvent

