editor_id_to_form = {
    "Heavy_Aetherium_Body": "Requiem.esp:0A1168",
    "Heavy_Aetherium_Feet": "Requiem.esp:0A1167",
    "Heavy_Aetherium_Hands": "Requiem.esp:0A1169",
    "Heavy_Aetherium_Head": "Requiem.esp:0A116A",
    "Heavy_Ahzidal_Body": "Dragonborn.esm:01DB97",
    "Heavy_Ahzidal_Feet": "Dragonborn.esm:01C655",
    "Heavy_Ahzidal_Hands": "Dragonborn.esm:01DB99",
    "Heavy_Ahzidal_Head": "Dragonborn.esm:01DB98",
    "Heavy_AicantarDwarven_Body": "Requiem.esp:ADDD81",
    "Heavy_AicantarDwarven_Feet": "Requiem.esp:ADDD82",
    "Heavy_AncientDragonplate_Body": "Requiem.esp:ADDD87",
    "Heavy_AncientDragonplate_Feet": "Requiem.esp:ADDD88",
    "Heavy_AncientDragonplate_Hands": "Requiem.esp:ADDD89",
    "Heavy_AncientDragonplate_Head": "Requiem.esp:ADDD8A",
    "Heavy_AncientNord_Body": "Skyrim.esm:018388",
    "Heavy_AncientNord_Feet": "Skyrim.esm:056A9D",
    "Heavy_AncientNord_Hands": "Skyrim.esm:056B17",
    "Heavy_AncientNord_Head": "Skyrim.esm:056A9E",
    "Heavy_AncientNord_Shield": "Skyrim.esm:01394B",
    "Heavy_Blades_Body": "Skyrim.esm:04B28B",
    "Heavy_Blades_Feet": "Skyrim.esm:04B288",
    "Heavy_Blades_Hands": "Skyrim.esm:04B28D",
    "Heavy_Blades_Head": "Skyrim.esm:04B28F",
    "Heavy_Blades_Shield": "Skyrim.esm:04F912",
    "Heavy_Bonemold_Body_Guard": "Dragonborn.esm:037564",
    "Heavy_Bonemold_Body_Pauldrons": "Dragonborn.esm:037563",
    "Heavy_Bonemold_Body": "Dragonborn.esm:01CD93",
    "Heavy_Bonemold_Feet": "Dragonborn.esm:01CD92",
    "Heavy_Bonemold_Hands": "Dragonborn.esm:01CD94",
    "Heavy_Bonemold_Head": "Dragonborn.esm:01CD95",
    "Heavy_Bonemold_Shield": "Dragonborn.esm:026234",
    "Heavy_Chieftain_Body": "Requiem.esp:ADDDAE",
    "Heavy_Chieftain_Feet": "Requiem.esp:ADDDAD",
    "Heavy_Chieftain_Hands": "Requiem.esp:ADDDAF",
    "Heavy_Chieftain_Head": "Requiem.esp:ADDDB0",
    "Heavy_Daedric_Body": "Skyrim.esm:01396B",
    "Heavy_Daedric_Feet": "Skyrim.esm:01396A",
    "Heavy_Daedric_Hands": "Skyrim.esm:01396C",
    "Heavy_Daedric_Head": "Skyrim.esm:01396D",
    "Heavy_Daedric_Shield": "Skyrim.esm:01396E",
    "Heavy_Dawnguard_Body_Dark": "Dawnguard.esm:00F3F7",
    "Heavy_Dawnguard_Body_Grey": "Dawnguard.esm:00F3FA",
    "Heavy_Dawnguard_Feet": "Dawnguard.esm:014757",
    "Heavy_Dawnguard_Hands": "Dawnguard.esm:014758",
    "Heavy_Dawnguard_Head": "Dawnguard.esm:0050D0",
    "Heavy_Dawnguard_Shield": "Dawnguard.esm:0150B8",
    "Heavy_Dragonplate_Body": "Skyrim.esm:013966",
    "Heavy_Dragonplate_Feet": "Skyrim.esm:013965",
    "Heavy_Dragonplate_Hands": "Skyrim.esm:013967",
    "Heavy_Dragonplate_Head": "Skyrim.esm:013969",
    "Heavy_Dragonplate_Shield": "Skyrim.esm:013968",
    "Heavy_Dremora_Body": "Skyrim.esm:0F1ABE",
    "Heavy_Dremora_Feet": "Skyrim.esm:0F1ABD",
    "Heavy_Dremora_Hands": "Skyrim.esm:0F1AC0",
    "Heavy_Dremora_Head": "Skyrim.esm:10F75F",
    "Heavy_DremoraPirate_Body": "Requiem.esp:ADDD90",
    "Heavy_DremoraPirate_Feet": "Requiem.esp:ADDD8F",
    "Heavy_DremoraPirate_Hands": "Requiem.esp:ADDD91",
    "Heavy_Dwarven_Body": "Skyrim.esm:01394D",
    "Heavy_Dwarven_Feet": "Skyrim.esm:01394C",
    "Heavy_Dwarven_Hands": "Skyrim.esm:01394E",
    "Heavy_Dwarven_Head": "Skyrim.esm:01394F",
    "Heavy_Dwarven_Shield": "Skyrim.esm:013950",
    "Heavy_Ebony_Body": "Skyrim.esm:013961",
    "Heavy_Ebony_Feet": "Skyrim.esm:013960",
    "Heavy_Ebony_Hands": "Skyrim.esm:013962",
    "Heavy_Ebony_Head": "Skyrim.esm:013963",
    "Heavy_Ebony_Shield": "Skyrim.esm:013964",
    "Heavy_FalmerHeavy_Body": "Dawnguard.esm:0023E9",
    "Heavy_FalmerHeavy_Feet": "Dawnguard.esm:0023EF",
    "Heavy_FalmerHeavy_Hands": "Dawnguard.esm:0023ED",
    "Heavy_FalmerHeavy_Head": "Dawnguard.esm:0023EB",
    "Heavy_Guard_Body_Eastmarch": "Requiem.esp:90E436",
    "Heavy_Guard_Body_Falkreath": "Requiem.esp:90E430",
    "Heavy_Guard_Body_Haafingar": "Requiem.esp:90E434",
    "Heavy_Guard_Body_Hjaalmarch": "Requiem.esp:90E432",
    "Heavy_Guard_Body_ThePale": "Requiem.esp:90E412",
    "Heavy_Guard_Body_TheReach": "Requiem.esp:90E431",
    "Heavy_Guard_Body_TheRift": "Requiem.esp:90E433",
    "Heavy_Guard_Body_Whiterun": "Requiem.esp:90E435",
    "Heavy_Guard_Body_Winterhold": "Requiem.esp:90E437",
    "Heavy_Halvar_Body": "Requiem.esp:ADDDB1",
    "Heavy_Halvar_Feet": "Requiem.esp:ADDDB2",
    "Heavy_Halvar_Hands": "Requiem.esp:ADDDB3",
    "Heavy_Halvar_Head": "Requiem.esp:ADDDB4",
    "Heavy_Imperial_Body": "Skyrim.esm:0136D5",
    "Heavy_Imperial_Feet": "Skyrim.esm:0136D6",
    "Heavy_Imperial_Hands": "Skyrim.esm:0136D4",
    "Heavy_Imperial_Head_Horseman": "Skyrim.esm:09610D",
    "Heavy_Imperial_Head": "Skyrim.esm:013EDC",
    "Heavy_Imperial_Shield": "Skyrim.esm:0135BA",
    "Heavy_ImperialLegate_Body": "Requiem.esp:00102E",
    "Heavy_ImperialLegate_Feet": "Requiem.esp:00102F",
    "Heavy_ImperialLegate_Hands": "Requiem.esp:00102D",
    "Heavy_ImperialLegate_Head": "Skyrim.esm:0136CF",
    "Heavy_ImprovedBonemold_Body": "Dragonborn.esm:03AB26",
    "Heavy_ImprovedBonemold_Feet": "Dragonborn.esm:03AB25",
    "Heavy_ImprovedBonemold_Hands": "Dragonborn.esm:03AB22",
    "Heavy_ImprovedBonemold_Head": "Dragonborn.esm:03AB23",
    "Heavy_ImprovedBonemold_Shield": "Dragonborn.esm:03AB24",
    "Heavy_Iron_Body_Pauldrons": "Skyrim.esm:013948",
    "Heavy_Iron_Body": "Skyrim.esm:012E49",
    "Heavy_Iron_Feet": "Skyrim.esm:012E4B",
    "Heavy_Iron_Hands": "Skyrim.esm:012E46",
    "Heavy_Iron_Head": "Skyrim.esm:012E4D",
    "Heavy_Iron_Shield_Dented": "Dragonborn.esm:03399C",
    "Heavy_Iron_Shield": "Skyrim.esm:012EB6",
    "Heavy_Quicksilver_Body": "Dragonborn.esm:01CD97",
    "Heavy_Quicksilver_Feet": "Dragonborn.esm:01CD96",
    "Heavy_Quicksilver_Hands": "Dragonborn.esm:01CD98",
    "Heavy_Quicksilver_Head": "Dragonborn.esm:01CD99",
    "Heavy_Quicksilver_Shield": "Dragonborn.esm:026236",
    "Heavy_Orcish_Body": "Skyrim.esm:013957",
    "Heavy_Orcish_Feet": "Skyrim.esm:013956",
    "Heavy_Orcish_Hands": "Skyrim.esm:013958",
    "Heavy_Orcish_Head": "Skyrim.esm:013959",
    "Heavy_Orcish_Shield": "Skyrim.esm:013946",
    "Heavy_SilverHand_Body": "Requiem.esp:ADDD93",
    "Heavy_SilverHand_Feet": "Requiem.esp:ADDD92",
    "Heavy_SilverHand_Hands": "Requiem.esp:ADDD94",
    "Heavy_SilverHand_Head": "Requiem.esp:ADDD95",
    "Heavy_SilverHandVeteran_Body": "Requiem.esp:ADDD97",
    "Heavy_SilverHandVeteran_Feet": "Requiem.esp:ADDD96",
    "Heavy_SilverHandVeteran_Hands": "Requiem.esp:ADDD98",
    "Heavy_SilverHandVeteran_Head": "Requiem.esp:ADDD99",
    "Heavy_Stalhrim_Body": "Dragonborn.esm:01CD9F",
    "Heavy_Stalhrim_Feet": "Dragonborn.esm:01CD9E",
    "Heavy_Stalhrim_Hands": "Dragonborn.esm:01CDA0",
    "Heavy_Stalhrim_Head": "Dragonborn.esm:01CDA1",
    "Heavy_Steel_Body_Pauldrons": "Skyrim.esm:0F6F22",
    "Heavy_Steel_Body": "Skyrim.esm:013952",
    "Heavy_Steel_Feet": "Skyrim.esm:013951",
    "Heavy_Steel_Hands": "Skyrim.esm:013953",
    "Heavy_Steel_Head_Horn": "Skyrim.esm:0F6F24",
    "Heavy_Steel_Head": "Skyrim.esm:013954",
    "Heavy_Steel_Shield": "Skyrim.esm:013955",
    "Heavy_SteelPlate_Body": "Skyrim.esm:01395C",
    "Heavy_SteelPlate_Feet": "Skyrim.esm:01395B",
    "Heavy_SteelPlate_Hands": "Skyrim.esm:01395D",
    "Heavy_SteelPlate_Head": "Skyrim.esm:01395E",
    "Heavy_StormcloakOfficer_Body": "Skyrim.esm:08697E",
    "Heavy_StormcloakOfficer_Feet": "Skyrim.esm:086981",
    "Heavy_StormcloakOfficer_Hands": "Skyrim.esm:086983",
    "Heavy_StormcloakOfficer_Head": "Skyrim.esm:086985",
    "Heavy_TheSkinner_Body": "Requiem.esp:ADDD9B",
    "Heavy_TheSkinner_Feet": "Requiem.esp:ADDD9A",
    "Heavy_TheSkinner_Hands": "Requiem.esp:ADDD9C",
    "Heavy_TheSkinner_Head": "Requiem.esp:ADDD9D",
    "Heavy_Tyranus_Body": "Requiem.esp:ADDDA6",
    "Heavy_Tyranus_Feet": "Requiem.esp:ADDDA5",
    "Heavy_Tyranus_Hands": "Requiem.esp:ADDDA7",
    "Heavy_Tyranus_Head": "Requiem.esp:ADDDA8",
    "Heavy_Vigilant_Body": "Requiem.esp:39C006",
    "Heavy_Vigilant_Feet": "Requiem.esp:39C007",
    "Heavy_Vigilant_Hands": "Requiem.esp:39C008",
    "Heavy_Vigilant_Head": "Requiem.esp:39C009",
    "Heavy_VvardenfellEbony_Body": "Requiem.esp:ADDD84",
    "Heavy_VvardenfellEbony_Feet": "Requiem.esp:ADDD83",
    "Heavy_VvardenfellEbony_Hands": "Requiem.esp:ADDD85",
    "Heavy_VvardenfellEbony_Head": "Requiem.esp:ADDD86",
    "Heavy_Wolf_Body": "Skyrim.esm:0CAE15",
    "Heavy_Wolf_Feet": "Skyrim.esm:0CEE7C",
    "Heavy_Wolf_Hands": "Skyrim.esm:0CEE7E",
    "Heavy_Wolf_Head": "Skyrim.esm:04C3D0",
    "Light_AlainElven_Body": "Requiem.esp:003E01",
    "Light_AlainElven_Feet": "Requiem.esp:003E02",
    "Light_AlainElven_Hands": "Requiem.esp:003E03",
    "Light_Alikr_Body": "Requiem.esp:ADDDA0",
    "Light_Alikr_Feet": "Requiem.esp:ADDDA1",
    "Light_Alikr_Hands": "Requiem.esp:ADDDA2",
    "Light_Alikr_Head": "Requiem.esp:ADDDA3",
    "Light_Alikr_Shield": "Requiem.esp:ADDDA4",
    "Light_AncientDragonscale_Body": "Requiem.esp:ADDD8B",
    "Light_AncientDragonscale_Feet": "Requiem.esp:ADDD8C",
    "Light_AncientDragonscale_Hands": "Requiem.esp:ADDD8D",
    "Light_AncientDragonscale_Head": "Requiem.esp:ADDD8E",
    "Light_AncientShrouded_Body": "Skyrim.esm:0E1F15",
    "Light_AncientShrouded_Feet": "Skyrim.esm:0E1F14",
    "Light_AncientShrouded_Hands": "Skyrim.esm:0E1F16",
    "Light_AncientShrouded_Head": "Skyrim.esm:0E1F17",
    "Light_Blackguard_Body": "Dragonborn.esm:02AD33",
    "Light_Blackguard_Feet": "Dragonborn.esm:02AD34",
    "Light_Blackguard_Hands": "Dragonborn.esm:02AD32",
    "Light_Blackguard_Head": "Dragonborn.esm:02AD31",
    "Light_Chainmail_Body": "Requiem.esp:ADDD69",
    "Light_Chainmail_Feet": "Requiem.esp:ADDD67",
    "Light_Chainmail_Hands": "Requiem.esp:ADDD68",
    "Light_Chainmail_Head": "Requiem.esp:ADDD66",
    "Light_Chitin_Body": "Dragonborn.esm:01CD87",
    "Light_Chitin_Feet": "Dragonborn.esm:01CD86",
    "Light_Chitin_Hands": "Dragonborn.esm:01CD88",
    "Light_Chitin_Head": "Dragonborn.esm:01CD89",
    "Light_Chitin_Shield": "Dragonborn.esm:026235",
    "Light_Dawnguard_Body_Dark": "Dawnguard.esm:00F404",
    "Light_Dawnguard_Body_Grey": "Dawnguard.esm:00F402",
    "Light_Dawnguard_Body_Red": "Dawnguard.esm:00F3FB",
    "Light_Dawnguard_Feet": "Dawnguard.esm:00F400",
    "Light_Dawnguard_Hands": "Dawnguard.esm:00F3FE",
    "Light_Dawnguard_Head": "Dawnguard.esm:01989E",
    "Light_Dragonscale_Body": "Skyrim.esm:01393E",
    "Light_Dragonscale_Feet": "Skyrim.esm:01393D",
    "Light_Dragonscale_Hands": "Skyrim.esm:01393F",
    "Light_Dragonscale_Head": "Skyrim.esm:013940",
    "Light_Dragonscale_Shield": "Skyrim.esm:013941",
    "Light_Dwarven_Body": "Requiem.esp:ADDD73",
    "Light_Dwarven_Feet": "Requiem.esp:ADDD72",
    "Light_Dwarven_Hands": "Requiem.esp:ADDD74",
    "Light_Dwarven_Head": "Requiem.esp:ADDD75",
    "Light_Elven_Body_Pauldrons": "Skyrim.esm:01392A",
    "Light_Elven_Body": "Skyrim.esm:0896A3",
    "Light_Elven_Feet": "Skyrim.esm:01391A",
    "Light_Elven_Hands": "Skyrim.esm:01391C",
    "Light_Elven_Head": "Skyrim.esm:01391D",
    "Light_Elven_Shield": "Skyrim.esm:01391E",
    "Light_Executioner_Body": "Skyrim.esm:0CF8B3",
    "Light_Executioner_Feet": "Skyrim.esm:0CF8B0",
    "Light_Executioner_Hands": "Skyrim.esm:0CF8B1",
    "Light_Executioner_Head": "Skyrim.esm:0CF8B2",
    "Light_Falmer_Body": "Skyrim.esm:0B83CB",
    "Light_Falmer_Feet": "Skyrim.esm:0B83CD",
    "Light_Falmer_Hands": "Skyrim.esm:0B83CF",
    "Light_Falmer_Head": "Skyrim.esm:04C3CB",
    "Light_Falmer_Shield": "Skyrim.esm:05C06C",
    "Light_Forsworn_Body": "Skyrim.esm:0D8D50",
    "Light_Forsworn_Feet": "Skyrim.esm:0D8D4E",
    "Light_Forsworn_Hands": "Skyrim.esm:0D8D55",
    "Light_Forsworn_Head": "Skyrim.esm:0D8D52",
    "Light_Fur_Body_Kilt": "Skyrim.esm:10594B",
    "Light_Fur_Body_KiltWithMantle": "Skyrim.esm:10594D",
    "Light_Fur_Body_Sleeves": "Skyrim.esm:06F393",
    "Light_Fur_Body": "Skyrim.esm:10594F",
    "Light_Fur_Feet": "Skyrim.esm:06F398",
    "Light_Fur_Hands": "Skyrim.esm:06F39B",
    "Light_Fur_Head": "Skyrim.esm:06F39E",
    "Light_Glass_Body": "Skyrim.esm:013939",
    "Light_Glass_Feet": "Skyrim.esm:013938",
    "Light_Glass_Hands": "Skyrim.esm:01393A",
    "Light_Glass_Head": "Skyrim.esm:01393B",
    "Light_Glass_Shield": "Skyrim.esm:01393C",
    "Light_Guard_Body_Falkreath": "Skyrim.esm:02151E",
    "Light_Guard_Body_Haafingar": "Skyrim.esm:0C7F5B",
    "Light_Guard_Body_Hjaalmarch": "Skyrim.esm:021520",
    "Light_Guard_Body_ThePale": "Skyrim.esm:021525",
    "Light_Guard_Body_TheReach": "Skyrim.esm:021508",
    "Light_Guard_Body_TheRift": "Skyrim.esm:021507",
    "Light_Guard_Body_Whiterun": "Skyrim.esm:02150D",
    "Light_Guard_Body_Winterhold": "Skyrim.esm:021522",
    "Light_Guard_Head_Falkreath": "Skyrim.esm:021619",
    "Light_Guard_Head_Haafingar": "Skyrim.esm:0C7F5C",
    "Light_Guard_Head_Hjaalmarch": "Skyrim.esm:02161B",
    "Light_Guard_Head_ThePale": "Skyrim.esm:02161F",
    "Light_Guard_Head_TheReach": "Skyrim.esm:021613",
    "Light_Guard_Head_TheRift": "Skyrim.esm:021622",
    "Light_Guard_Head_Whiterun": "Skyrim.esm:021615",
    "Light_Guard_Head_Winterhold": "Skyrim.esm:02161D",
    "Light_Guard_Head": "Requiem.esp:A2B164",
    "Light_Guard_Shield_Eastmarch": "Skyrim.esm:0214EB",
    "Light_Guard_Shield_Falkreath": "Skyrim.esm:0214ED",
    "Light_Guard_Shield_Haafingar": "Skyrim.esm:0214F4",
    "Light_Guard_Shield_Hjaalmarch": "Skyrim.esm:0214EF",
    "Light_Guard_Shield_ThePale": "Skyrim.esm:0214F7",
    "Light_Guard_Shield_TheReach": "Skyrim.esm:0214DC",
    "Light_Guard_Shield_TheRift": "Skyrim.esm:0214BA",
    "Light_Guard_Shield_Whiterun": "Skyrim.esm:0214E0",
    "Light_Guard_Shield_Winterhold": "Skyrim.esm:0214F1",
    "Light_Hide_Body_Studded": "Skyrim.esm:01B3A2",
    "Light_Hide_Body": "Skyrim.esm:013911",
    "Light_Hide_Feet": "Skyrim.esm:013910",
    "Light_Hide_Hands": "Skyrim.esm:013912",
    "Light_Hide_Head": "Skyrim.esm:013913",
    "Light_Hide_Shield": "Skyrim.esm:013914",
    "Light_Imperial_Body_Studded": "Skyrim.esm:013ED8",
    "Light_Imperial_Body_Tullius": "Skyrim.esm:05CBFE",
    "Light_Imperial_Body": "Skyrim.esm:013ED9",
    "Light_Imperial_Feet": "Skyrim.esm:013ED7",
    "Light_Imperial_Hands": "Skyrim.esm:013EDA",
    "Light_Imperial_Head": "Skyrim.esm:013EDB",
    "Light_Imperial_Shield": "Skyrim.esm:013AB2",
    "Light_Leather_Body": "Skyrim.esm:03619E",
    "Light_Leather_Feet": "Skyrim.esm:013920",
    "Light_Leather_Hands": "Skyrim.esm:013921",
    "Light_Leather_Head_Hood": "Skyrim.esm:0EE5C0",
    "Light_Leather_Head": "Skyrim.esm:013922",
    "Light_Linwe_Body": "Skyrim.esm:108544",
    "Light_Linwe_Feet": "Skyrim.esm:108543",
    "Light_Linwe_Hands": "Skyrim.esm:108545",
    "Light_Linwe_Head": "Skyrim.esm:108546",
    "Light_MoragTong_Body": "Dragonborn.esm:0292AC",
    "Light_MoragTong_Feet": "Dragonborn.esm:0292AB",
    "Light_MoragTong_Hands": "Dragonborn.esm:0292AD",
    "Light_MoragTong_Head": "Dragonborn.esm:0292AE",
    "Light_NetchLeather_Body_Boiled": "Requiem.esp:ADDD7A",
    "Light_NetchLeather_Body": "Requiem.esp:ADDD7D",
    "Light_NetchLeather_Feet": "Requiem.esp:ADDD7E",
    "Light_NetchLeather_Hands": "Requiem.esp:ADDD7F",
    "Light_NetchLeather_Head_Boiled": "Requiem.esp:ADDD79",
    "Light_NetchLeather_Head": "Requiem.esp:ADDD80",
    "Light_NetchLeather_Shield_Tower": "Requiem.esp:ADDD7B",
    "Light_NetchLeather_Shield": "Requiem.esp:ADDD7C",
    "Light_Nightingale_Body": "Skyrim.esm:0FCC0F",
    "Light_Nightingale_Feet": "Skyrim.esm:0FCC0D",
    "Light_Nightingale_Hands": "Skyrim.esm:0FCC11",
    "Light_Nightingale_Head": "Skyrim.esm:0FCC12",
    "Light_Orcish_Body": "Requiem.esp:ADDDAA",
    "Light_Orcish_Feet": "Requiem.esp:ADDDA9",
    "Light_Orcish_Hands": "Requiem.esp:ADDDAB",
    "Light_Orcish_Head": "Requiem.esp:ADDDAC",
    "Light_PenitusOculatus_Body": "Skyrim.esm:0D3EA0",
    "Light_PenitusOculatus_Feet": "Skyrim.esm:0D3EA7",
    "Light_PenitusOculatus_Hands": "Skyrim.esm:0D3EAB",
    "Light_PenitusOculatus_Head": "Skyrim.esm:0D3EAA",
    "Light_ReinforcedChitin_Body": "Dragonborn.esm:01CD8A",
    "Light_ReinforcedChitin_Feet": "Dragonborn.esm:01CD82",
    "Light_ReinforcedChitin_Hands": "Dragonborn.esm:01CD8B",
    "Light_ReinforcedChitin_Head": "Dragonborn.esm:01CD8C",
    "Light_Scale_Body_Horn": "Skyrim.esm:01B3A4",
    "Light_Scale_Body": "Skyrim.esm:01B3A3",
    "Light_Scale_Feet": "Skyrim.esm:01B39F",
    "Light_Scale_Hands": "Skyrim.esm:01B3A0",
    "Light_Scale_Head": "Skyrim.esm:01B3A1",
    "Light_Shrouded_Body_Sleeveless": "Skyrim.esm:05ABC3",
    "Light_Shrouded_Body": "Skyrim.esm:0D2844",
    "Light_Shrouded_Feet": "Skyrim.esm:0D2845",
    "Light_Shrouded_Hands": "Skyrim.esm:0D2843",
    "Light_Shrouded_Head_Masked": "Skyrim.esm:0D2842",
    "Light_Shrouded_Head": "Skyrim.esm:05ABC4",
    "Light_Skaal_Body": "Dragonborn.esm:03910E",
    "Light_Skaal_Feet": "Dragonborn.esm:039112",
    "Light_Skaal_Hands": "Dragonborn.esm:039110",
    "Light_Skaal_Head": "Dragonborn.esm:039114",
    "Light_SnowElf_Body_Pauldrons": "Dawnguard.esm:00C816",
    "Light_SnowElf_Body": "Dawnguard.esm:00CAD3",
    "Light_SnowElf_Feet": "Dawnguard.esm:00C815",
    "Light_SnowElf_Hands": "Dawnguard.esm:00C817",
    "Light_SnowElf_Head": "Dawnguard.esm:00C814",
    "Light_Stalhrim_Body": "Dragonborn.esm:01CDA2",
    "Light_Stalhrim_Feet": "Dragonborn.esm:01CD7E",
    "Light_Stalhrim_Hands": "Dragonborn.esm:01CDA5",
    "Light_Stalhrim_Head": "Dragonborn.esm:01CDA3",
    "Light_Stalhrim_Shield": "Dragonborn.esm:026237",
    "Light_Stormcloak_Body": "Skyrim.esm:0A6D7B",
    "Light_Stormcloak_Feet": "Skyrim.esm:0A6D7F",
    "Light_Stormcloak_Hands": "Skyrim.esm:0A6D7D",
    "Light_Stormcloak_Head": "Skyrim.esm:0A6D79",
    "Light_SummersetShadows_Body": "Skyrim.esm:108540",
    "Light_SummersetShadows_Feet": "Skyrim.esm:10853F",
    "Light_SummersetShadows_Hands": "Skyrim.esm:108541",
    "Light_SummersetShadows_Head": "Skyrim.esm:108542",
    "Light_ThievesGuild_Body": "Skyrim.esm:0D3AC3",
    "Light_ThievesGuild_Feet": "Skyrim.esm:0D3AC2",
    "Light_ThievesGuild_Hands": "Skyrim.esm:0D3AC4",
    "Light_ThievesGuild_Head": "Skyrim.esm:0D3AC5",
    "Light_ThievesGuildKarliah_Body": "Skyrim.esm:0E35E8",
    "Light_ThievesGuildKarliah_Feet": "Skyrim.esm:0E35E7",
    "Light_ThievesGuildKarliah_Hands": "Skyrim.esm:0E35E9",
    "Light_ThievesGuildKarliah_Head": "Skyrim.esm:0E35EA",
    "Light_ThievesGuildMaster_Body": "Skyrim.esm:0E35D7",
    "Light_ThievesGuildMaster_Feet": "Skyrim.esm:0E35D6",
    "Light_ThievesGuildMaster_Hands": "Skyrim.esm:0E35D8",
    "Light_ThievesGuildMaster_Head": "Skyrim.esm:0E35D9",
    "Light_Tsun_Body": "Skyrim.esm:0C0165",
    "Light_Tsun_Feet": "Skyrim.esm:0C0166",
    "Light_Ulfric_Body": "Requiem.esp:ADDD76",
    "Light_Ulfric_Feet": "Requiem.esp:ADDD77",
    "Light_Ulfric_Hands": "Requiem.esp:ADDD78",
    "Light_Vampire_Body_Dark": "Dawnguard.esm:0142C7",
    "Light_Vampire_Body_Gray": "Dawnguard.esm:0191F2",
    "Light_Vampire_Body_Red": "Dawnguard.esm:0191F3",
    "Light_Vampire_Body_Royal": "Dawnguard.esm:00B5DB",
    "Light_Vampire_Body_Valerica": "Dawnguard.esm:0194C5",
    "Light_Vampire_Feet": "Dawnguard.esm:00B5DE",
    "Light_Vampire_Hands": "Dawnguard.esm:01A51F",
    "Light_WornShrouded_Body": "Skyrim.esm:10EB5B",
    "Light_WornShrouded_Feet": "Skyrim.esm:10EB5C",
    "Light_WornShrouded_Hands": "Skyrim.esm:10EB5E",
    "Light_WornShrouded_Head": "Skyrim.esm:10EB5D",
    "Weapon_Alikr_Sword": "Requiem.esp:ADDD6E",
    "Weapon_Amber_DaiKatana": "Requiem.esp:ADDEC1",
    "Weapon_Amber_Katana": "Requiem.esp:ADDEBE",
    "Weapon_Amber_Tanto": "Requiem.esp:ADDEC3",
    "Weapon_Amber_Wakizashi": "Requiem.esp:ADDEC2",
    "Weapon_AncientNord_Battleaxe": "Skyrim.esm:01CB64",
    "Weapon_AncientNord_Bow": "Skyrim.esm:0302CA",
    "Weapon_AncientNord_Greatsword": "Skyrim.esm:0236A5",
    "Weapon_AncientNord_Shortsword": "Requiem.esp:ADDF13",
    "Weapon_AncientNord_Sword": "Skyrim.esm:02C66F",
    "Weapon_AncientNord_WarAxe": "Skyrim.esm:02C672",
    "Weapon_AncientNordHoned_Battleaxe": "Skyrim.esm:05BF12",
    "Weapon_AncientNordHoned_Bow": "Skyrim.esm:05D179",
    "Weapon_AncientNordHoned_Greatsword": "Skyrim.esm:05BF13",
    "Weapon_AncientNordHoned_Shortsword": "Requiem.esp:ADDF14",
    "Weapon_AncientNordHoned_Sword": "Skyrim.esm:05BF14",
    "Weapon_AncientNordHoned_WarAxe": "Skyrim.esm:05BF15",
    "Weapon_Blades_DaiKatana": "Requiem.esp:ADDF6E",
    "Weapon_Blades_Katana": "Skyrim.esm:03AEB9",
    "Weapon_Blades_Tanto": "Requiem.esp:ADDF6F",
    "Weapon_Blades_Wakizashi": "Requiem.esp:ADDF70",
    "Weapon_Bound_Battleaxe": "Skyrim.esm:058F5E",
    "Weapon_Bound_Bow": "Skyrim.esm:058F60",
    "Weapon_Bound_Dagger": "Dragonborn.esm:01CE02",
    "Weapon_Bound_Sword_RightHand": "Skyrim.esm:0BA30E",
    "Weapon_Bound_Sword": "Skyrim.esm:058F5F",
    "Weapon_BoundMystic_Battleaxe": "Skyrim.esm:0424F7",
    "Weapon_BoundMystic_Bow": "Skyrim.esm:0424F8",
    "Weapon_BoundMystic_Dagger": "Dragonborn.esm:01CE03",
    "Weapon_BoundMystic_Sword": "Skyrim.esm:0424F9",
    "Weapon_Daedric_Battleaxe": "Skyrim.esm:0139B4",
    "Weapon_Daedric_Battlestaff": "Requiem.esp:06B47F",
    "Weapon_Daedric_Bow": "Skyrim.esm:0139B5",
    "Weapon_Daedric_Crossbow": "Requiem.esp:8F7F91",
    "Weapon_Daedric_Dagger": "Skyrim.esm:0139B6",
    "Weapon_Daedric_DaiKatana": "Requiem.esp:ADDE0D",
    "Weapon_Daedric_Greatsword": "Skyrim.esm:0139B7",
    "Weapon_Daedric_Katana": "Requiem.esp:ADDE0A",
    "Weapon_Daedric_Mace": "Skyrim.esm:0139B8",
    "Weapon_Daedric_Quarterstaff": "Requiem.esp:ADDF27",
    "Weapon_Daedric_Shortsword": "Requiem.esp:ADDEF4",
    "Weapon_Daedric_Sword": "Skyrim.esm:0139B9",
    "Weapon_Daedric_Tanto": "Requiem.esp:ADDE0C",
    "Weapon_Daedric_Wakizashi": "Requiem.esp:ADDE0B",
    "Weapon_Daedric_WarAxe": "Skyrim.esm:0139B3",
    "Weapon_Daedric_Warhammer": "Skyrim.esm:0139BA",
    "Weapon_Dark_DaiKatana": "Requiem.esp:ADDED9",
    "Weapon_Dark_Katana": "Requiem.esp:ADDED6",
    "Weapon_Dark_Tanto": "Requiem.esp:ADDED8",
    "Weapon_Dark_Wakizashi": "Requiem.esp:ADDED7",
    "Weapon_Dawnguard_Battleaxe": "Requiem.esp:ADDF5F",
    "Weapon_Dawnguard_Crossbow": "Requiem.esp:AD3746",
    "Weapon_Dawnguard_Mace": "Requiem.esp:ADDF60",
    "Weapon_Dawnguard_Quarterstaff": "Requiem.esp:ADDF61",
    "Weapon_Dawnguard_WarAxe": "Dawnguard.esm:00D098",
    "Weapon_Dawnguard_Warhammer": "Dawnguard.esm:00DD55",
    "Weapon_DawnguardImproved_Crossbow": "Dawnguard.esm:00F19E",
    "Weapon_Dragonbone_Battleaxe": "Dawnguard.esm:014FC3",
    "Weapon_Dragonbone_Bow": "Dawnguard.esm:0176F1",
    "Weapon_Dragonbone_Crossbow": "Requiem.esp:8F7F92",
    "Weapon_Dragonbone_Dagger": "Dawnguard.esm:014FCB",
    "Weapon_Dragonbone_DaiKatana": "Requiem.esp:ADDE2F",
    "Weapon_Dragonbone_Greatsword": "Dawnguard.esm:014FCC",
    "Weapon_Dragonbone_Katana": "Requiem.esp:ADDE2E",
    "Weapon_Dragonbone_Mace": "Dawnguard.esm:014FCD",
    "Weapon_Dragonbone_Quarterstaff": "Requiem.esp:ADDF63",
    "Weapon_Dragonbone_Shortsword": "Requiem.esp:ADDF62",
    "Weapon_Dragonbone_Sword": "Dawnguard.esm:014FCE",
    "Weapon_Dragonbone_Tanto": "Requiem.esp:ADDE30",
    "Weapon_Dragonbone_Wakizashi": "Requiem.esp:ADDE31",
    "Weapon_Dragonbone_WarAxe": "Dawnguard.esm:014FCF",
    "Weapon_Dragonbone_Warhammer": "Dawnguard.esm:014FD0",
    "Weapon_Dwarven_Battleaxe": "Skyrim.esm:013994",
    "Weapon_Dwarven_Bow": "Skyrim.esm:013995",
    "Weapon_Dwarven_Crossbow": "Dawnguard.esm:00B647",
    "Weapon_Dwarven_Dagger": "Skyrim.esm:013996",
    "Weapon_Dwarven_DaiKatana": "Requiem.esp:ADDE78",
    "Weapon_Dwarven_Greatsword": "Skyrim.esm:013997",
    "Weapon_Dwarven_Katana": "Requiem.esp:ADDE75",
    "Weapon_Dwarven_Mace": "Skyrim.esm:013998",
    "Weapon_Dwarven_Quarterstaff": "Requiem.esp:ADDF2B",
    "Weapon_Dwarven_Shortsword": "Requiem.esp:ADDEF5",
    "Weapon_Dwarven_Sword": "Skyrim.esm:013999",
    "Weapon_Dwarven_Tanto": "Requiem.esp:ADDE77",
    "Weapon_Dwarven_Wakizashi": "Requiem.esp:ADDE76",
    "Weapon_Dwarven_WarAxe": "Skyrim.esm:013993",
    "Weapon_Dwarven_Warhammer": "Skyrim.esm:01399A",
    "Weapon_Dwemer_Crossbow": "Requiem.esp:AD3747",
    "Weapon_DwemerImproved_Crossbow": "Dawnguard.esm:00F19F",
    "Weapon_Ebony_Battleaxe": "Skyrim.esm:0139AC",
    "Weapon_Ebony_Battlestaff": "Requiem.esp:06B47E",
    "Weapon_Ebony_Bow": "Skyrim.esm:0139AD",
    "Weapon_Ebony_Crossbow": "Requiem.esp:8F7F90",
    "Weapon_Ebony_Dagger": "Skyrim.esm:0139AE",
    "Weapon_Ebony_DaiKatana": "Requiem.esp:ADDE11",
    "Weapon_Ebony_Greatsword": "Skyrim.esm:0139AF",
    "Weapon_Ebony_Katana": "Requiem.esp:ADDE0E",
    "Weapon_Ebony_Mace": "Skyrim.esm:0139B0",
    "Weapon_Ebony_Quarterstaff": "Requiem.esp:ADDF28",
    "Weapon_Ebony_Shortsword": "Requiem.esp:ADDEF6",
    "Weapon_Ebony_Sword": "Skyrim.esm:0139B1",
    "Weapon_Ebony_Tanto": "Requiem.esp:ADDE10",
    "Weapon_Ebony_Wakizashi": "Requiem.esp:ADDE0F",
    "Weapon_Ebony_WarAxe": "Skyrim.esm:0139AB",
    "Weapon_Ebony_Warhammer": "Skyrim.esm:0139B2",
    "Weapon_Elven_Battleaxe": "Skyrim.esm:01399C",
    "Weapon_Elven_Bow": "Skyrim.esm:01399D",
    "Weapon_Elven_Crossbow": "Requiem.esp:899DBD",
    "Weapon_Elven_Dagger": "Skyrim.esm:01399E",
    "Weapon_Elven_DaiKatana": "Requiem.esp:ADDE7D",
    "Weapon_Elven_Greatsword": "Skyrim.esm:01399F",
    "Weapon_Elven_Katana": "Requiem.esp:ADDE7A",
    "Weapon_Elven_Mace": "Skyrim.esm:0139A0",
    "Weapon_Elven_Quarterstaff": "Requiem.esp:ADDF29",
    "Weapon_Elven_Shortsword": "Requiem.esp:ADDEF7",
    "Weapon_Elven_Sword": "Skyrim.esm:0139A1",
    "Weapon_Elven_Tanto": "Requiem.esp:ADDE7C",
    "Weapon_Elven_Wakizashi": "Requiem.esp:ADDE7B",
    "Weapon_Elven_WarAxe": "Skyrim.esm:01399B",
    "Weapon_Elven_Warhammer": "Skyrim.esm:0139A2",
    "Weapon_Falmer_Bow": "Skyrim.esm:038340",
    "Weapon_Falmer_Sword": "Skyrim.esm:02E6D1",
    "Weapon_Falmer_WarAxe": "Skyrim.esm:0302CD",
    "Weapon_FalmerHoned_Bow": "Skyrim.esm:083167",
    "Weapon_FalmerHoned_Sword": "Skyrim.esm:06F6FF",
    "Weapon_FalmerHoned_WarAxe": "Skyrim.esm:06F700",
    "Weapon_Forsworn_Bow": "Skyrim.esm:0CEE9B",
    "Weapon_Forsworn_Dagger": "Requiem.esp:ADDFAE",
    "Weapon_Forsworn_Sword": "Skyrim.esm:0CADE9",
    "Weapon_Forsworn_WarAxe": "Skyrim.esm:0CC829",
    "Weapon_Glass_Battleaxe": "Skyrim.esm:0139A4",
    "Weapon_Glass_Battlestaff": "Requiem.esp:06B479",
    "Weapon_Glass_Bow": "Skyrim.esm:0139A5",
    "Weapon_Glass_Crossbow": "Requiem.esp:8F7F85",
    "Weapon_Glass_Dagger": "Skyrim.esm:0139A6",
    "Weapon_Glass_DaiKatana": "Requiem.esp:ADDE62",
    "Weapon_Glass_Greatsword": "Skyrim.esm:0139A7",
    "Weapon_Glass_Katana": "Requiem.esp:ADDE5A",
    "Weapon_Glass_Mace": "Skyrim.esm:0139A8",
    "Weapon_Glass_Quarterstaff": "Requiem.esp:ADDF1F",
    "Weapon_Glass_Shortsword": "Requiem.esp:ADDEF8",
    "Weapon_Glass_Sword": "Skyrim.esm:0139A9",
    "Weapon_Glass_Tanto": "Requiem.esp:ADDE63",
    "Weapon_Glass_Wakizashi": "Requiem.esp:ADDE61",
    "Weapon_Glass_WarAxe": "Skyrim.esm:0139A3",
    "Weapon_Glass_Warhammer": "Skyrim.esm:0139AA",
    "Weapon_Golden_DaiKatana": "Requiem.esp:ADDED3",
    "Weapon_Golden_Katana": "Requiem.esp:ADDED2",
    "Weapon_Golden_Tanto": "Requiem.esp:ADDED5",
    "Weapon_Golden_Wakizashi": "Requiem.esp:ADDED4",
    "Weapon_Imperial_Bow": "Skyrim.esm:013841",
    "Weapon_Imperial_Dagger": "Requiem.esp:7F8C37",
    "Weapon_Imperial_Mace": "Requiem.esp:7F8C33",
    "Weapon_Imperial_Shortsword": "Requiem.esp:7F8C38",
    "Weapon_Imperial_Sword": "Skyrim.esm:0135B8",
    "Weapon_Iron_Battleaxe": "Skyrim.esm:013980",
    "Weapon_Iron_Battlestaff": "Requiem.esp:06B466",
    "Weapon_Iron_Bow": "Skyrim.esm:03B562",
    "Weapon_Iron_Club": "Requiem.esp:ADDF1D",
    "Weapon_Iron_Crossbow": "Requiem.esp:8F7F8E",
    "Weapon_Iron_Dagger": "Skyrim.esm:01397E",
    "Weapon_Iron_Greatsword": "Skyrim.esm:01359D",
    "Weapon_Iron_Mace": "Skyrim.esm:013982",
    "Weapon_Iron_Quarterstaff": "Requiem.esp:ADDF7B",
    "Weapon_Iron_Shortsword": "Requiem.esp:ADDEF9",
    "Weapon_Iron_Sword": "Skyrim.esm:012EB7",
    "Weapon_Iron_WarAxe": "Skyrim.esm:013790",
    "Weapon_Iron_Warhammer": "Skyrim.esm:013981",
    "Weapon_Madness_DaiKatana": "Requiem.esp:ADDEB1",
    "Weapon_Madness_Katana": "Requiem.esp:ADDEAA",
    "Weapon_Madness_Tanto": "Requiem.esp:ADDEB3",
    "Weapon_Madness_Wakizashi": "Requiem.esp:ADDEB2",
    "Weapon_NordHero_Battleaxe": "Skyrim.esm:068C79",
    "Weapon_NordHero_Bow": "Skyrim.esm:068C57",
    "Weapon_NordHero_Greatsword": "Skyrim.esm:0A3115",
    "Weapon_NordHero_Shortsword": "Requiem.esp:ADDF15",
    "Weapon_NordHero_Sword": "Skyrim.esm:068C7B",
    "Weapon_NordHero_WarAxe": "Skyrim.esm:068C63",
    "Weapon_Quicksilver_Battleaxe": "Dragonborn.esm:01CDAD",
    "Weapon_Quicksilver_Bow": "Dragonborn.esm:026232",
    "Weapon_Quicksilver_Dagger": "Dragonborn.esm:01CDAE",
    "Weapon_Quicksilver_DaiKatana": "Requiem.esp:ADDE42",
    "Weapon_Quicksilver_Greatsword": "Dragonborn.esm:01CDAF",
    "Weapon_Quicksilver_Katana": "Requiem.esp:ADDE3B",
    "Weapon_Quicksilver_Mace": "Dragonborn.esm:01CDB0",
    "Weapon_Quicksilver_Quarterstaff": "Requiem.esp:ADDF4C",
    "Weapon_Quicksilver_Shortsword": "Requiem.esp:ADDF4B",
    "Weapon_Quicksilver_Sword": "Dragonborn.esm:01CDB1",
    "Weapon_Quicksilver_Tanto": "Requiem.esp:ADDE41",
    "Weapon_Quicksilver_Wakizashi": "Requiem.esp:ADDE43",
    "Weapon_Quicksilver_WarAxe": "Dragonborn.esm:01CDB2",
    "Weapon_Quicksilver_Warhammer": "Dragonborn.esm:01CDB3",
    "Weapon_Orcish_Battleaxe": "Skyrim.esm:01398C",
    "Weapon_Orcish_Bow": "Skyrim.esm:01398D",
    "Weapon_Orcish_Crossbow": "Requiem.esp:899DB6",
    "Weapon_Orcish_Dagger": "Skyrim.esm:01398E",
    "Weapon_Orcish_DaiKatana": "Requiem.esp:ADDE8A",
    "Weapon_Orcish_Greatsword": "Skyrim.esm:01398F",
    "Weapon_Orcish_Katana": "Requiem.esp:ADDE7E",
    "Weapon_Orcish_Mace": "Skyrim.esm:013990",
    "Weapon_Orcish_Quarterstaff": "Requiem.esp:ADDF48",
    "Weapon_Orcish_Shortsword": "Requiem.esp:ADDEFA",
    "Weapon_Orcish_Sword": "Skyrim.esm:013991",
    "Weapon_Orcish_Tanto": "Requiem.esp:ADDE80",
    "Weapon_Orcish_Wakizashi": "Requiem.esp:ADDE7F",
    "Weapon_Orcish_WarAxe": "Skyrim.esm:01398B",
    "Weapon_Orcish_Warhammer": "Skyrim.esm:013992",
    "Weapon_Redguard_Sword": "Skyrim.esm:07A91A",
    "Weapon_Silver_Battleaxe": "Requiem.esp:ADDF88",
    "Weapon_Silver_Battlestaff": "Requiem.esp:06B471",
    "Weapon_Silver_Dagger": "Requiem.esp:ADDF3F",
    "Weapon_Silver_DaiKatana": "Requiem.esp:ADDE9D",
    "Weapon_Silver_Greatsword": "Skyrim.esm:10C6FB",
    "Weapon_Silver_Katana": "Requiem.esp:ADDE9A",
    "Weapon_Silver_Mace": "Requiem.esp:ADDF42",
    "Weapon_Silver_Quarterstaff": "Requiem.esp:ADDF75",
    "Weapon_Silver_Shortsword": "Requiem.esp:ADDF0F",
    "Weapon_Silver_Sword": "Skyrim.esm:10AA19",
    "Weapon_Silver_Tanto": "Requiem.esp:ADDEA2",
    "Weapon_Silver_Wakizashi": "Requiem.esp:ADDEA1",
    "Weapon_Silver_WarAxe": "Requiem.esp:ADDF87",
    "Weapon_Silver_Warhammer": "Requiem.esp:ADDF43",
    "Weapon_SkyforgeSteel_Battleaxe": "Skyrim.esm:09F25F",
    "Weapon_SkyforgeSteel_Dagger": "Skyrim.esm:09F25D",
    "Weapon_SkyforgeSteel_Greatsword": "Skyrim.esm:09F25E",
    "Weapon_SkyforgeSteel_Quarterstaff": "Requiem.esp:ADDF8D",
    "Weapon_SkyforgeSteel_Shortsword": "Requiem.esp:ADDF11",
    "Weapon_SkyforgeSteel_Sword": "Skyrim.esm:09F25C",
    "Weapon_SkyforgeSteel_WarAxe": "Skyrim.esm:09F260",
    "Weapon_Spectral_Battleaxe": "Skyrim.esm:0F82FA",
    "Weapon_Spectral_Bow": "Skyrim.esm:0F82FC",
    "Weapon_Spectral_Sword": "Skyrim.esm:0F71DD",
    "Weapon_Stalhrim_Battleaxe": "Dragonborn.esm:01CDB4",
    "Weapon_Stalhrim_Bow": "Dragonborn.esm:026231",
    "Weapon_Stalhrim_Dagger": "Dragonborn.esm:01CDB5",
    "Weapon_Stalhrim_DaiKatana": "Requiem.esp:ADDE51",
    "Weapon_Stalhrim_Greatsword": "Dragonborn.esm:01CDB6",
    "Weapon_Stalhrim_Katana": "Requiem.esp:ADDE4B",
    "Weapon_Stalhrim_Mace": "Dragonborn.esm:01CDB7",
    "Weapon_Stalhrim_Quarterstaff": "Requiem.esp:ADDF4D",
    "Weapon_Stalhrim_Shortsword": "Requiem.esp:ADDF4E",
    "Weapon_Stalhrim_Sword": "Dragonborn.esm:01CDB8",
    "Weapon_Stalhrim_Tanto": "Requiem.esp:ADDE52",
    "Weapon_Stalhrim_Wakizashi": "Requiem.esp:ADDE53",
    "Weapon_Stalhrim_WarAxe": "Dragonborn.esm:01CDB9",
    "Weapon_Stalhrim_Warhammer": "Dragonborn.esm:01CDBA",
    "Weapon_Steel_Battleaxe": "Skyrim.esm:013984",
    "Weapon_Steel_Battlestaff": "Requiem.esp:06B46A",
    "Weapon_Steel_Bow": "Skyrim.esm:013985",
    "Weapon_Steel_Club": "Requiem.esp:ADDF1E",
    "Weapon_Steel_Crossbow": "Dawnguard.esm:000801",
    "Weapon_Steel_Dagger": "Skyrim.esm:013986",
    "Weapon_Steel_DaiKatana": "Requiem.esp:ADDE09",
    "Weapon_Steel_Greatsword": "Skyrim.esm:013987",
    "Weapon_Steel_Katana": "Requiem.esp:ADDE06",
    "Weapon_Steel_Mace": "Skyrim.esm:013988",
    "Weapon_Steel_Quarterstaff": "Requiem.esp:ADDF23",
    "Weapon_Steel_Shortsword": "Requiem.esp:ADDEFB",
    "Weapon_Steel_Sword": "Skyrim.esm:013989",
    "Weapon_Steel_Tanto": "Requiem.esp:ADDE07",
    "Weapon_Steel_Wakizashi": "Requiem.esp:ADDE08",
    "Weapon_Steel_WarAxe": "Skyrim.esm:013983",
    "Weapon_Steel_Warhammer": "Skyrim.esm:01398A",
    "Weapon_Wood_Battlestaff": "Requiem.esp:06B492",
    "Weapon_Wood_Club": "Requiem.esp:ADDF7D",
    "Weapon_Wood_Crossbow": "Requiem.esp:8F7F8F",
    "Weapon_Wood_Quarterstaff": "Requiem.esp:ADDF7C",
    "Weapon_Wood_Sword": "HearthFires.esm:004D91",
}

load_order = [
    "Skyrim.esm",
    "Update.esm",
    "Dawnguard.esm",
    "HearthFires.esm",
    "Dragonborn.esm",
    "ccasvsse001-almsivi.esm",
    "ccBGSSSE001-Fish.esm",
    "ccbgssse002-exoticarrows.esl",
    "ccbgssse003-zombies.esl",
    "ccbgssse004-ruinsedge.esl",
    "ccbgssse005-goldbrand.esl",
    "ccbgssse006-stendarshammer.esl",
    "ccbgssse007-chrysamere.esl",
    "ccbgssse010-petdwarvenarmoredmudcrab.esl",
    "ccbgssse011-hrsarmrelvn.esl",
    "ccbgssse012-hrsarmrstl.esl",
    "ccbgssse014-spellpack01.esl",
    "ccbgssse019-staffofsheogorath.esl",
    "ccbgssse020-graycowl.esl",
    "ccbgssse021-lordsmail.esl",
    "ccmtysse001-knightsofthenine.esl",
    "ccQDRSSE001-SurvivalMode.esl",
    "cctwbsse001-puzzledungeon.esm",
    "cceejsse001-hstead.esm",
    "ccqdrsse002-firewood.esl",
    "ccbgssse018-shadowrend.esl",
    "ccbgssse035-petnhound.esl",
    "ccfsvsse001-backpacks.esl",
    "cceejsse002-tower.esl",
    "ccedhsse001-norjewel.esl",
    "ccvsvsse002-pets.esl",
    "ccBGSSSE037-Curios.esl",
    "ccbgssse034-mntuni.esl",
    "ccbgssse045-hasedoki.esl",
    "ccbgssse008-wraithguard.esl",
    "ccbgssse036-petbwolf.esl",
    "ccffbsse001-imperialdragon.esl",
    "ccmtysse002-ve.esl",
    "ccbgssse043-crosselv.esl",
    "ccvsvsse001-winter.esl",
    "cceejsse003-hollow.esl",
    "ccbgssse016-umbra.esm",
    "ccbgssse031-advcyrus.esm",
    "ccbgssse038-bowofshadows.esl",
    "ccbgssse040-advobgobs.esl",
    "ccbgssse050-ba_daedric.esl",
    "ccbgssse052-ba_iron.esl",
    "ccbgssse054-ba_orcish.esl",
    "ccbgssse058-ba_steel.esl",
    "ccbgssse059-ba_dragonplate.esl",
    "ccbgssse061-ba_dwarven.esl",
    "ccpewsse002-armsofchaos.esl",
    "ccbgssse041-netchleather.esl",
    "ccedhsse002-splkntset.esl",
    "ccbgssse064-ba_elven.esl",
    "ccbgssse063-ba_ebony.esl",
    "ccbgssse062-ba_dwarvenmail.esl",
    "ccbgssse060-ba_dragonscale.esl",
    "ccbgssse056-ba_silver.esl",
    "ccbgssse055-ba_orcishscaled.esl",
    "ccbgssse053-ba_leather.esl",
    "ccbgssse051-ba_daedricmail.esl",
    "ccbgssse057-ba_stalhrim.esl",
    "ccbgssse066-staves.esl",
    "ccbgssse067-daedinv.esm",
    "ccbgssse068-bloodfall.esl",
    "ccbgssse069-contest.esl",
    "ccvsvsse003-necroarts.esl",
    "ccvsvsse004-beafarmer.esl",
    "ccBGSSSE025-AdvDSGS.esm",
    "ccffbsse002-crossbowpack.esl",
    "ccbgssse013-dawnfang.esl",
    "ccrmssse001-necrohouse.esl",
    "ccedhsse003-redguard.esl",
    "cceejsse004-hall.esl",
    "cceejsse005-cave.esm",
    "cckrtsse001_altar.esl",
    "cccbhsse001-gaunt.esl",
    "ccafdsse001-dwesanctuary.esm",
    "Unofficial Skyrim Special Edition Patch.esp",
    "Unofficial Skyrim Creation Club Content Patch.esl",
    "SkyUI_SE.esp",
    "Requiem.esp",
]


def form_id_pair_to_load_order_form_id(form_id_pair: str) -> int:
    plugin, fixed_form_id = form_id_pair.split(":")
    return load_order.index(plugin) * 0x1000000 + int(fixed_form_id, 16)
