name: spriggit

on:
  pull_request:
    branches: [ main ]

jobs:
  spriggit:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.*

      - name: Download Spriggit
        run: gh release download -O .github/spriggit.zip -p "SpriggitLinuxCLI.zip" -R Mutagen-Modding/Spriggit
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Extract Spriggit
        run: 7z x .github/spriggit.zip -o.github/spriggit

      - name: Prepare Spriggit executable
        run: chmod +x .github/spriggit/Spriggit.CLI

      - name: Convert "Requiem.esp" to Spriggit format
        run: .github/spriggit/Spriggit.CLI convert-from-plugin --InputPath "Requiem.esp" --OutputPath "components/plugins/Requiem.esp" --GameRelease SkyrimSE --PackageName Spriggit.Yaml

      - name: Convert "Requiem - Creation Club.esp" to Spriggit format
        run: .github/spriggit/Spriggit.CLI convert-from-plugin --InputPath "Requiem - Creation Club.esp" --OutputPath "components/plugins/Requiem - Creation Club.esp" --GameRelease SkyrimSE --PackageName Spriggit.Yaml

      - name: Commit changed files (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: components/plugins/*
          commit_message: 'ci: convert plugins to spriggit format'
