name: spriggit

on:
  pull_request:
    branches: [ main ]

jobs:
  spriggit:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - run: wget -O .github/spriggit.zip https://github.com/Mutagen-Modding/Spriggit/releases/latest/download/SpriggitLinuxCLI.zip

      - run: 7z x .github/spriggit.zip -o.github/spriggit

      - run: chmod +x .github/spriggit/Spriggit.CLI
      
      - run: .github/spriggit/Spriggit.CLI convert-from-plugin --InputPath "Requiem.esp" --OutputPath "components/plugins/Requiem.esp" --GameRelease SkyrimSE --PackageName Spriggit.Yaml

      - run: .github/spriggit/Spriggit.CLI convert-from-plugin --InputPath "Requiem - Creation Club.esp" --OutputPath "components/plugins/Requiem - Creation Club.esp" --GameRelease SkyrimSE --PackageName Spriggit.Yaml

      - uses: stefanzweifel/git-auto-commit-action@v5
