name: spriggit

on:
  pull_request:
    branches: [ main ]

jobs:
  spriggit:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - run: gh release download -O .github/spriggit.zip -p "SpriggitLinuxCLI.zip" -R Mutagen-Modding/Spriggit
        env:
          GH_TOKEN: ${{ github.token }}

      - run: 7z x .github/spriggit.zip -o.github/spriggit

      - run: chmod +x .github/spriggit/Spriggit.CLI

      - run: dotnet tool install Spriggit.Yaml.Skyrim --version 0.37.1 --tool-path "Spriggit/Translations/Spriggit.Yaml.Skyrim/0.37.1"

      - run: .github/spriggit/Spriggit.CLI convert-from-plugin --InputPath "Requiem.esp" --OutputPath "components/plugins/Requiem.esp" --GameRelease SkyrimSE --PackageName Spriggit.Yaml

      - run: .github/spriggit/Spriggit.CLI convert-from-plugin --InputPath "Requiem - Creation Club.esp" --OutputPath "components/plugins/Requiem - Creation Club.esp" --GameRelease SkyrimSE --PackageName Spriggit.Yaml

      - uses: stefanzweifel/git-auto-commit-action@v5
